name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        # Include full git history needed for `yarn changeset status`
        with:
          ref: ${{github.event.pull_request.head.sha}}
          fetch-depth: 0
      - name: Setup Node.js
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and build
        id: install
        run: |
          yarn install
          echo --- >> .changeset/empty-lib-changeset.md
          echo '"@srchase/pkg-c": patch' >> .changeset/empty-lib-changeset.md
          echo --- >> .changeset/empty-lib-changeset.md
          echo "" >> .changeset/empty-lib-changeset.md
          echo "empty changeset" >> .changeset/empty-lib-changeset.md
          cat .changeset/empty-lib-changeset.md
          git config user.name "Chase Coalwell"
          git config user.email "782571+srchase@users.noreply.github.com"
          git add .changeset/empty-lib-changeset.md
          git commit -m 'throwaway commit'
          yarn changeset status --since=origin/main
