name: RELEASE

on:
  workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Publish to NPM
        id: changsets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
          NPM_TOKEN: ${{  secrets.NPM_TOKEN }}
      - name: Success Notification
        if: steps.changesets.outputs.published == 'true'
        run: echo 'publish success'
      - name: Failure Notification
        if: steps.changesets.outputs.published != 'true'
        run: echo 'publish failed'
