name: RELEASE

on:
  workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Version
        id: version
        run: |
          yarn changeset version
          echo "porcelain=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
      - name: Notify 0 packages to publish
        if: steps.version.outputs.porcelain == '0'
        run: echo "no packages to publish"
      - name: Commit
        id: commit
        if: steps.version.outputs.porcelain != '0'
        run: |
          git config user.name "Chase Coalwell"
          git config user.email "782571+srchase@users.noreply.github.com"
          git add .
          echo "packages=$(git diff --name-only | grep package.json | wc -l)" >> $GITHUB_OUTPUT
          git commit -m 'Verison packages'
          git push
      - name: Release
        id: release
        uses: changesets/action@v1
        if: steps.commit.outcome == 'success'
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Success Notification
        if: steps.release.outputs.published == 'true'
        run: echo 'publish success'
      - name: Failure Notification
        if: steps.release.outputs.published != 'true' && steps.version.outputs.porcelain != '0'
        run: echo 'publish failed'
